
batch 0 of 13 done
batch 1 of 13 done
batch 2 of 13 done
batch 3 of 13 done
batch 4 of 13 done
batch 5 of 13 done
batch 6 of 13 done
batch 7 of 13 done
batch 8 of 13 done
batch 9 of 13 done
batch 10 of 13 done
batch 11 of 13 done
batch 12 of 13 done
number of rows: Index(['aircraft_carrier', 'album', 'almond', 'altar', 'anvil', 'baby',
       'baklava', 'bamboo', 'baseball_bat', 'batter',
       ...
       'vase', 'vent', 'wetsuit', 'whale', 'wheel', 'whistle', 'window',
       'wine_bottle', 'wrapping_paper', 'zebra'],
      dtype='object', name='things_id', length=216)
epoch 0 done
Exception ignored in: <function _releaseLock at 0x7f0f18a42c10>
Traceback (most recent call last):
  File "/SOFTWARE/anaconda3/lib/python3.8/logging/__init__.py", line 223, in _releaseLock
    def _releaseLock():
KeyboardInterrupt:
Traceback (most recent call last):
  File "fine_tune.py", line 273, in <module>
    train_epoch_losses, val_epoch_losses = run(config, train_dataset, val_dataset)
  File "fine_tune.py", line 173, in run
    train_epoch_loss = train(train_loader, model, criterion, optimizer, epoch, train_dataset)
  File "fine_tune.py", line 56, in train
    loss, loss_similar, loss_dissimilar, cosine_distance, cosine_sim = criterion(output1, output2, label)
  File "/home/hhansen/decon/decon_env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hhansen/DecontextEmbeddings/scripts/retraining/loss.py", line 60, in forward
    cosine_sim = F.cosine_similarity(output1, output2)
KeyboardInterrupt